spring.application.name=zookeeper
server.port=8084

info.app.version=@project.version@

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.metrics.tags.application=${spring.application.name}
