spring.application.name=service2
server.port=8083

info.app.version=@project.version@

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99
