spring.application.name=rate-printer
server.port=8082

info.app.version=@project.version@

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.metrics.tags.application=${spring.application.name}
